units:
  px: cx + 2
  py: cy + 2

  pushX: (cx / 2)
  pushY: (cy / 2)

  padX: pushX + 2
  padY: pushY + 2

  pad: 2

  spacing: 0.75

  kx: cx + spacing
  ky: cy + spacing

  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: 1.5
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0

points:
  key:
    padding: cy + spacing
    spread: cx + spacing
  zones:
    matrix:
      anchor:
        shift: [50, -150]
        rotate: 2
      columns:
        outer:
          key:
            column_net: P020
        pinky:
          key:
            origin: [-12, -19]
            stagger: 2
            splay: -2
            column_net: P022
        ring:
          key:
            stagger: 2
            column_net: P024
        middle:
          key:
            stagger: 2
            column_net: P100
        index:
          key:
            stagger: -2
            column_net: P011
        inner:
          rows.mod.skip: true
          key:
            stagger: -2
            column_net: P017
      rows:
        mod:
          row_net: P113
        bottom:
          row_net: P115
        home:
          row_net: P002
        top:
          row_net: P029
        num:
          row_net: P031
    thumbfan:
      anchor:
        ref: matrix_inner_mod
        shift: [0, -0.4kx]
      columns:
        left:
          key:
            height: 1.5cx
            splay: -5
            column_net: P017
        home:
          rows.thumb.height: 1.5cx
          key:
            spread: 21
            stagger: -1.75
            splay: -10
            column_net: P104
        far:
          rows.thumb.height: 1.5cx
          key:
            spread: 21.75
            stagger: -2.85
            splay: -15
            column_net: P106
      rows:
        thumb:
          row_net: P113
    indexfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [kx + 1, -0.75]
      columns:
        close:
          key:
            splay: -5
            column_net: P104
        far:
          key:
            spread: kx + 1.5
            stagger: -1.75
            splay: -10
            column_net: P106
      rows:
        index:
          row_net: P115
  mirror:
    ref: matrix_inner_num
    distance: 120
outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
      fillet: 0

  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num
          shift: [-padX, padY]
        - ref: matrix_outer_mod
          shift: [-padX, -padY]
        - ref: matrix_outer_mod
          shift: [pushX - 1, -padY]
        - ref: matrix_pinky_mod
          shift: [-pushX + 1, -padY]
        - ref: matrix_pinky_mod
          shift: [pushX - 1, -padY]
        - ref: matrix_ring_mod
          shift: [-pushX + 1, -padY]
        - ref: matrix_ring_mod
          shift: [pushX - 1, -padY]
        - ref: matrix_middle_mod
          shift: [-pushX + 1, -padY]
        - ref: matrix_middle_mod
          shift: [pushX - 1, -padY]
        - ref: matrix_index_mod
          shift: [-pushX + 1, -padY]
        - ref: matrix_index_mod
          shift: [7.75, -padY]
        - ref: thumbfan_left_thumb
          shift: [-padX, -pushY - padY/2]
        - ref: thumbfan_home_thumb
          shift: [-pushX, -pushY - padY/2]
        - ref: thumbfan_far_thumb
          shift: [-padX, -pushY - padY /2]
        - ref: thumbfan_far_thumb
          shift: [padX, -pushY - padY /2]
        - ref: thumbfan_far_thumb
          shift: [padX, pushY + padY/2]
        - ref: thumbfan_far_thumb
          shift: [-3, pushY + padY/2]
        - ref: indexfan_far_index
          shift: [padX, padY]
        - ref: indexfan_far_index
          shift: [-pushX -0.75, padY]
        - ref: matrix_inner_bottom
          shift: [3padX, padY]
        - ref: matrix_inner_num
          shift: [3padX, padY]
        - ref: matrix_inner_num
          shift: [-pushX + 1, padY]
        - ref: matrix_index_num
          shift: [pushX - 1, padY]
        - ref: matrix_index_num
          shift: [-pushX + 1, padY]
        - ref: matrix_middle_num
          shift: [pushX - 1, padY]
        - ref: matrix_middle_num
          shift: [-pushX + 1, padY]
        - ref: matrix_ring_num
          shift: [pushX - 1, padY]
        - ref: matrix_ring_num
          shift: [-pushX + 1, padY]
        - ref: matrix_pinky_num
          shift: [pushX - 1, padY]
        - ref: matrix_pinky_num
          shift: [-pushX + 1, padY]
        - ref: matrix_outer_num
          shift: [pushX, padY]

  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_outer_num
          shift: [-padX, padY]
        - ref: mirror_matrix_outer_mod
          shift: [-padX, -padY]
        - ref: mirror_matrix_outer_mod
          shift: [pushX - 1, -padY]
        - ref: mirror_matrix_pinky_mod
          shift: [-pushX + 1, -padY]
        - ref: mirror_matrix_pinky_mod
          shift: [pushX - 1, -padY]
        - ref: mirror_matrix_ring_mod
          shift: [-pushX + 1, -padY]
        - ref: mirror_matrix_ring_mod
          shift: [pushX - 1, -padY]
        - ref: mirror_matrix_middle_mod
          shift: [-pushX + 1, -padY]
        - ref: mirror_matrix_middle_mod
          shift: [pushX - 1, -padY]
        - ref: mirror_matrix_index_mod
          shift: [-pushX + 1, -padY]
        - ref: mirror_matrix_index_mod
          shift: [7.75, -padY]
        - ref: mirror_thumbfan_left_thumb
          shift: [-padX, -pushY - padY/2]
        - ref: mirror_thumbfan_home_thumb
          shift: [-pushX, -pushY - padY/2]
        - ref: mirror_thumbfan_far_thumb
          shift: [-padX, -pushY - padY /2]
        - ref: mirror_thumbfan_far_thumb
          shift: [padX, -pushY - padY /2]
        - ref: mirror_thumbfan_far_thumb
          shift: [padX, pushY + padY/2]
        - ref: mirror_thumbfan_far_thumb
          shift: [-3, pushY + padY/2]
        - ref: mirror_indexfan_far_index
          shift: [padX, padY]
        - ref: mirror_indexfan_far_index
          shift: [-pushX -0.75, padY]
        - ref: mirror_matrix_inner_bottom
          shift: [3padX, padY]
        - ref: mirror_matrix_inner_num
          shift: [3padX, padY]
        - ref: mirror_matrix_inner_num
          shift: [-pushX + 1, padY]
        - ref: mirror_matrix_index_num
          shift: [pushX - 1, padY]
        - ref: mirror_matrix_index_num
          shift: [-pushX + 1, padY]
        - ref: mirror_matrix_middle_num
          shift: [pushX - 1, padY]
        - ref: mirror_matrix_middle_num
          shift: [-pushX + 1, padY]
        - ref: mirror_matrix_ring_num
          shift: [pushX - 1, padY]
        - ref: mirror_matrix_ring_num
          shift: [-pushX + 1, padY]
        - ref: mirror_matrix_pinky_num
          shift: [pushX - 1, padY]
        - ref: mirror_matrix_pinky_num
          shift: [-pushX + 1, padY]
        - ref: mirror_matrix_outer_num
          shift: [pushX, padY]

  case_left:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-padX - caseBorder, padY + caseBorder]
        - ref: matrix_outer_mod
          shift: [-padX - caseBorder, -padY - caseBorder]
        - ref: matrix_outer_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: matrix_pinky_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: matrix_pinky_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: matrix_ring_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: matrix_ring_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: matrix_middle_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: matrix_middle_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: matrix_index_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: matrix_index_mod
          shift: [7.75 - caseBorder, -padY - caseBorder]
        - ref: thumbfan_left_thumb
          shift: [-padX - caseBorder, -pushY - padY/2 - caseBorder]
        - ref: thumbfan_home_thumb
          shift: [-pushX, -pushY - padY/2 - caseBorder]
        - ref: thumbfan_far_thumb
          shift: [-padX, -pushY - padY/2 - caseBorder]
        - ref: thumbfan_far_thumb
          shift: [padX + caseBorder, -pushY - padY/2 - caseBorder]
        - ref: thumbfan_far_thumb
          shift: [padX + caseBorder, pushY + padY/2 + caseBorder]
        - ref: thumbfan_far_thumb
          shift: [-3 + caseBorder, pushY + padY/2 + caseBorder]
        - ref: indexfan_far_index
          shift: [padX + caseBorder, padY + caseBorder]
        - ref: indexfan_far_index
          shift: [-pushX -0.75 + caseBorder, padY + caseBorder]
        - ref: matrix_inner_bottom
          shift: [3padX + caseBorder, padY + caseBorder]
        - ref: matrix_inner_num
          shift: [3padX + caseBorder, padY + caseBorder]
        - ref: matrix_inner_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: matrix_index_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: matrix_index_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: matrix_middle_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: matrix_middle_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: matrix_ring_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: matrix_ring_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: matrix_pinky_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: matrix_pinky_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: matrix_outer_num
          shift: [pushX, padY + caseBorder]

  case_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_num
          shift: [-padX - caseBorder, padY + caseBorder]
        - ref: mirror_matrix_outer_mod
          shift: [-padX - caseBorder, -padY - caseBorder]
        - ref: mirror_matrix_outer_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: mirror_matrix_pinky_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: mirror_matrix_pinky_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: mirror_matrix_ring_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: mirror_matrix_ring_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: mirror_matrix_middle_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: mirror_matrix_middle_mod
          shift: [pushX - 1, -padY - caseBorder]
        - ref: mirror_matrix_index_mod
          shift: [-pushX + 1, -padY - caseBorder]
        - ref: mirror_matrix_index_mod
          shift: [7.75 - caseBorder, -padY - caseBorder]
        - ref: mirror_thumbfan_left_thumb
          shift: [-padX - caseBorder, -pushY - padY/2 - caseBorder]
        - ref: mirror_thumbfan_home_thumb
          shift: [-pushX, -pushY - padY/2 - caseBorder]
        - ref: mirror_thumbfan_far_thumb
          shift: [-padX, -pushY - padY/2 - caseBorder]
        - ref: mirror_thumbfan_far_thumb
          shift: [padX + caseBorder, -pushY - padY/2 - caseBorder]
        - ref: mirror_thumbfan_far_thumb
          shift: [padX + caseBorder, pushY + padY/2 + caseBorder]
        - ref: mirror_thumbfan_far_thumb
          shift: [-3 + caseBorder, pushY + padY/2 + caseBorder]
        - ref: mirror_indexfan_far_index
          shift: [padX + caseBorder, padY + caseBorder]
        - ref: mirror_indexfan_far_index
          shift: [-pushX -0.75 + caseBorder, padY + caseBorder]
        - ref: mirror_matrix_inner_bottom
          shift: [3padX + caseBorder, padY + caseBorder]
        - ref: mirror_matrix_inner_num
          shift: [3padX + caseBorder, padY + caseBorder]
        - ref: mirror_matrix_inner_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: mirror_matrix_index_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: mirror_matrix_index_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: mirror_matrix_middle_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: mirror_matrix_middle_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: mirror_matrix_ring_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: mirror_matrix_ring_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: mirror_matrix_pinky_num
          shift: [pushX - 1, padY + caseBorder]
        - ref: mirror_matrix_pinky_num
          shift: [-pushX + 1, padY + caseBorder]
        - ref: mirror_matrix_outer_num
          shift: [pushX, padY + caseBorder]

  left_board_key_cutouts:
    - name: board_left
    - operation: subtract
      name: keys

  right_board_key_cutouts:
    - name: board_right
    - operation: subtract
      name: keys

  # For visualisation
  visual:
    - name: board_left
    - operation: subtract
      name: keys
    - operation: stack
      name: case_left
    - name: board_right
    - operation: subtract
      name: keys
    - operation: stack
      name: case_right

pcbs:
  zyno_left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^matrix_.*|^thumbfan_.*|^indexfan_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode_main:
        what: diode
        where: /^matrix_.*|^thumbfan_.*|^indexfan_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90

      nice_nano:
        what: nice_nano
        where:
          ref: matrix_inner_num
        adjust:
          shift: [2padX - 1, -pushY]
          rotate: 270

      battery_connector:
        what: jstph
        where:
          ref: matrix_inner_home
          shift: [12, -5.5]
          rotate: 90
        params:
          side: B 
          pos: pos
          neg: GND

      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_inner_home
          shift: [30.75, 6]
          rotate: -90.0

      battery_switch:
        what: slider
        where:
          ref: matrix_inner_home
          shift: [30.5, -3.0]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      
      hole_bottom_right:
        what: mountinghole
        where:
          ref: indexfan_close_index
          shift: [pushX, -padY - 2pad]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: matrix_outer_bottom
          shift: [pushX + 1, -pushY - pad]
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_pinky_num
          shift: [-pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_inner_top
          shift: [-pushX - 0.4, pushY + 0.8]
      hole_center:
        what: mountinghole
        where:
          ref: matrix_middle_bottom
          shift: [pushX + 0.5, pushY - 1.2]

      front_text: &text
        what: text
        where: &textWhere
            ref: matrix_inner_home
            shift: [padX, pushY]
        params: &textParams
            text: Zyno
            justify: left
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4

  zyno_right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^mirror_matrix_.*|^mirror_thumbfan_.*|^mirror_indexfan_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode_main:
        what: diode
        where: /^mirror_matrix_.*|^mirror_thumbfan_.*|^mirror_indexfan_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, -3.5]
          rotate: -90

      nice_nano:
        what: nice_nano
        where:
          ref: mirror_matrix_inner_num
        adjust:
          shift: [2padX - 1, -pushY]
          rotate: 90

      battery_connector:
        what: jstph
        where:
          ref: mirror_matrix_inner_home
          shift: [12, -5.5]
          rotate: 90
        params:
          side: B 
          pos: pos
          neg: GND

      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_inner_home
          shift: [30.75, 6]
          rotate: -90.0

      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_inner_home
          shift: [30.5, -3.0]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_indexfan_close_index
          shift: [pushX, -padY - 2pad]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_matrix_outer_bottom
          shift: [pushX, -pushY]
      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_matrix_pinky_num
          shift: [-pushX - pad, -pushY - 1]
      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_matrix_inner_top
          shift: [-pushX - 0.4, pushY - 1.2]
      hole_center:
        what: mountinghole
        where:
          ref: mirror_matrix_middle_bottom
          shift: [pushX + 0.5, pushY - 3.2]

      front_text: &text
        what: text
        where: &textWhere
            ref: mirror_matrix_inner_home
            shift: [padX + padX, pushY]
        params: &textParams
            text: Zyno
            justify: left
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4

cases:
  plate:
    - name: case_left
      extrude: 1.2